inputs:
- name: sts4
- name: s3-manifest-yaml-vsix-snapshot
- name: s3-boot-properties-vsix-snapshot
- name: s3-boot-java-vsix-snapshot
- name: s3-concourse-vsix-snapshot
outputs:
- name: website
platform: linux
image_resource:
  type: docker-image
  source:
    repository: kdvolder/sts4-build-env
run:
  path: "sts4/concourse/tasks/build-website.sh"
