inputs:
- name: sts4
outputs:
- name: sts4-out
platform: linux
image_resource:
  type: docker-image
  source:
    repository: kdvolder/sts4-build-env
run:
  path: sts4/concourse/tasks/bump-package-json-versions.sh
