inputs:
- name: theia-version
- name: sts4
outputs:
- name: out
platform: linux
image_resource:
  type: docker-image
  source:
    repository: kdvolder/sts4-build-env
run:
  path: sts4/concourse/tasks/bump-theia-versions.sh
