platform: linux
image_resource:
  type: docker-image
  source:
    username: ((docker_hub_username))
    password: ((docker_hub_password))
    repository: springci/sts4-build-env
inputs:
- name: sources_repo
- name: tasks
run:
  path: tasks/concourse/tasks/npm-publish.sh
params:
  npm_token: npm-auth-token-for-publishing
  sources_dir: path-within-sources-repo