inputs:
- name: sts4
- name: maven-cache
- name: version
outputs:
- name: out
platform: linux
run:
  path: sts4/concourse/tasks/rc-build.sh
params:
  extension_id: undefined_extension_id
image_resource:
  type: docker-image
  source:
    username: ((docker_hub_username))
    password: ((docker_hub_password))
    repository: springci/sts4-build-env
  