name: Snapshot - Eclipse LS Extensions

concurrency:
  group: snapshot-all
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:

  language-servers-multiplatform-build:
    uses: ./.github/workflows/multiplatform-ls-build.yml
    with:
      java_version: '21'
      skip_tests: false
    secrets: inherit

  eclipse-ls-extensions:
    needs: [ language-servers-multiplatform-build ]
    uses: ./.github/workflows/eclipse-ls-extensions-build.yml
    with:
      eclipse_profile: 'e434'
      build_type: 'snapshot'
      skip_tests: true
    secrets: inherit

  e434-distro:
    needs: [ eclipse-ls-extensions ]
    uses: ./.github/workflows/gh-hosted-eclipse-distro-build.yml
    with:
      eclipse_profile: 'e434'
      build_type: 'snapshot'
      java_version: '21'
    secrets: inherit

  e435-distro:
    needs: [ eclipse-ls-extensions ]
    uses: ./.github/workflows/gh-hosted-eclipse-distro-build.yml
    with:
      eclipse_profile: 'e435'
      build_type: 'snapshot'
      java_version: '21'
    secrets: inherit

  e436-distro:
    needs: [ eclipse-ls-extensions ]
    uses: ./.github/workflows/gh-hosted-eclipse-distro-build.yml
    with:
      eclipse_profile: 'e436'
      build_type: 'snapshot'
      java_version: '21'
    secrets: inherit

  vscode-spring-boot:
    needs: [ language-servers-multiplatform-build ]
    uses: ./.github/workflows/snapshot-vscode-extension.yml
    with:
      extension-name: vscode-spring-boot
    secrets: inherit

  vscode-concourse:
    needs: [ language-servers-multiplatform-build ]
    uses: ./.github/workflows/snapshot-vscode-extension.yml
    with:
      extension-name: vscode-concourse
    secrets: inherit

  vscode-manifest-yaml:
    needs: [ language-servers-multiplatform-build ]
    uses: ./.github/workflows/snapshot-vscode-extension.yml
    with:
      extension-name: vscode-manifest-yaml
    secrets: inherit

  vscode-bosh:
    needs: [ language-servers-multiplatform-build ]
    uses: ./.github/workflows/snapshot-vscode-extension.yml
    with:
      extension-name: vscode-bosh
    secrets: inherit
