name: Snapshot - Eclipse LS Extensions

concurrency:
  group: eclipse-ls-extension-snapshot
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  eclipse-ls-extensions:
    uses: ./.github/workflows/eclipse-ls-extensions-build.yml
    with:
      eclipse_profile: 'e429'
      build_type: 'snapshot'
    secrets: inherit
